// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	client "github.com/moby/moby/client"

	mock "github.com/stretchr/testify/mock"
)

// MockDockerClient is an autogenerated mock type for the dockerClient type
type MockDockerClient struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockDockerClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerCreate provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) ContainerCreate(ctx context.Context, options client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerCreate")
	}

	var r0 client.ContainerCreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) (client.ContainerCreateResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) client.ContainerCreateResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ContainerCreateResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ContainerCreateOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerInspect provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerInspect(ctx context.Context, containerID string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 client.ContainerInspectResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) (client.ContainerInspectResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) client.ContainerInspectResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerInspectResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerInspectOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerList provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) ContainerList(ctx context.Context, options client.ContainerListOptions) (client.ContainerListResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 client.ContainerListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ContainerListOptions) (client.ContainerListResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ContainerListOptions) client.ContainerListResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ContainerListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ContainerListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerLogs provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerLogs(ctx context.Context, containerID string, options client.ContainerLogsOptions) (client.ContainerLogsResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 client.ContainerLogsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) (client.ContainerLogsResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) client.ContainerLogsResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ContainerLogsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerLogsOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerRemove provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerRemove(ctx context.Context, containerID string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 client.ContainerRemoveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) client.ContainerRemoveResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerRemoveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerRemoveOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerRestart provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerRestart(ctx context.Context, containerID string, options client.ContainerRestartOptions) (client.ContainerRestartResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRestart")
	}

	var r0 client.ContainerRestartResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerRestartOptions) (client.ContainerRestartResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerRestartOptions) client.ContainerRestartResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerRestartResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerRestartOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerStart provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerStart(ctx context.Context, containerID string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 client.ContainerStartResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) (client.ContainerStartResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) client.ContainerStartResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStartResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerStartOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerStop provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ContainerStop(ctx context.Context, containerID string, options client.ContainerStopOptions) (client.ContainerStopResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 client.ContainerStopResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) (client.ContainerStopResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) client.ContainerStopResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ContainerStopResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ContainerStopOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecAttach provides a mock function with given fields: ctx, execID, options
func (_m *MockDockerClient) ExecAttach(ctx context.Context, execID string, options client.ExecAttachOptions) (client.ExecAttachResult, error) {
	ret := _m.Called(ctx, execID, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecAttach")
	}

	var r0 client.ExecAttachResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecAttachOptions) (client.ExecAttachResult, error)); ok {
		return rf(ctx, execID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecAttachOptions) client.ExecAttachResult); ok {
		r0 = rf(ctx, execID, options)
	} else {
		r0 = ret.Get(0).(client.ExecAttachResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ExecAttachOptions) error); ok {
		r1 = rf(ctx, execID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecCreate provides a mock function with given fields: ctx, containerID, options
func (_m *MockDockerClient) ExecCreate(ctx context.Context, containerID string, options client.ExecCreateOptions) (client.ExecCreateResult, error) {
	ret := _m.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecCreate")
	}

	var r0 client.ExecCreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecCreateOptions) (client.ExecCreateResult, error)); ok {
		return rf(ctx, containerID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecCreateOptions) client.ExecCreateResult); ok {
		r0 = rf(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.ExecCreateResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ExecCreateOptions) error); ok {
		r1 = rf(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecInspect provides a mock function with given fields: ctx, execID, options
func (_m *MockDockerClient) ExecInspect(ctx context.Context, execID string, options client.ExecInspectOptions) (client.ExecInspectResult, error) {
	ret := _m.Called(ctx, execID, options)

	if len(ret) == 0 {
		panic("no return value specified for ExecInspect")
	}

	var r0 client.ExecInspectResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecInspectOptions) (client.ExecInspectResult, error)); ok {
		return rf(ctx, execID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ExecInspectOptions) client.ExecInspectResult); ok {
		r0 = rf(ctx, execID, options)
	} else {
		r0 = ret.Get(0).(client.ExecInspectResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ExecInspectOptions) error); ok {
		r1 = rf(ctx, execID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageInspect provides a mock function with given fields: ctx, imageID, inspectOpts
func (_m *MockDockerClient) ImageInspect(ctx context.Context, imageID string, inspectOpts ...client.ImageInspectOption) (client.ImageInspectResult, error) {
	_va := make([]interface{}, len(inspectOpts))
	for _i := range inspectOpts {
		_va[_i] = inspectOpts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, imageID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ImageInspect")
	}

	var r0 client.ImageInspectResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) (client.ImageInspectResult, error)); ok {
		return rf(ctx, imageID, inspectOpts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) client.ImageInspectResult); ok {
		r0 = rf(ctx, imageID, inspectOpts...)
	} else {
		r0 = ret.Get(0).(client.ImageInspectResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.ImageInspectOption) error); ok {
		r1 = rf(ctx, imageID, inspectOpts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageList provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) ImageList(ctx context.Context, options client.ImageListOptions) (client.ImageListResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageList")
	}

	var r0 client.ImageListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) (client.ImageListResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) client.ImageListResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ImageListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ImageListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImagePull provides a mock function with given fields: ctx, refStr, options
func (_m *MockDockerClient) ImagePull(ctx context.Context, refStr string, options client.ImagePullOptions) (client.ImagePullResponse, error) {
	ret := _m.Called(ctx, refStr, options)

	if len(ret) == 0 {
		panic("no return value specified for ImagePull")
	}

	var r0 client.ImagePullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImagePullOptions) (client.ImagePullResponse, error)); ok {
		return rf(ctx, refStr, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImagePullOptions) client.ImagePullResponse); ok {
		r0 = rf(ctx, refStr, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImagePullResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ImagePullOptions) error); ok {
		r1 = rf(ctx, refStr, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImagePush provides a mock function with given fields: ctx, image, options
func (_m *MockDockerClient) ImagePush(ctx context.Context, image string, options client.ImagePushOptions) (client.ImagePushResponse, error) {
	ret := _m.Called(ctx, image, options)

	if len(ret) == 0 {
		panic("no return value specified for ImagePush")
	}

	var r0 client.ImagePushResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImagePushOptions) (client.ImagePushResponse, error)); ok {
		return rf(ctx, image, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImagePushOptions) client.ImagePushResponse); ok {
		r0 = rf(ctx, image, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImagePushResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ImagePushOptions) error); ok {
		r1 = rf(ctx, image, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageRemove provides a mock function with given fields: ctx, imageID, options
func (_m *MockDockerClient) ImageRemove(ctx context.Context, imageID string, options client.ImageRemoveOptions) (client.ImageRemoveResult, error) {
	ret := _m.Called(ctx, imageID, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageRemove")
	}

	var r0 client.ImageRemoveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) (client.ImageRemoveResult, error)); ok {
		return rf(ctx, imageID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) client.ImageRemoveResult); ok {
		r0 = rf(ctx, imageID, options)
	} else {
		r0 = ret.Get(0).(client.ImageRemoveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.ImageRemoveOptions) error); ok {
		r1 = rf(ctx, imageID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageTag provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) ImageTag(ctx context.Context, options client.ImageTagOptions) (client.ImageTagResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageTag")
	}

	var r0 client.ImageTagResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ImageTagOptions) (client.ImageTagResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ImageTagOptions) client.ImageTagResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ImageTagResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ImageTagOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Info provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) Info(ctx context.Context, options client.InfoOptions) (client.SystemInfoResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 client.SystemInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.InfoOptions) (client.SystemInfoResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.InfoOptions) client.SystemInfoResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.SystemInfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.InfoOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) Ping(ctx context.Context, options client.PingOptions) (client.PingResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 client.PingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.PingOptions) (client.PingResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.PingOptions) client.PingResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.PingResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.PingOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServerVersion provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) ServerVersion(ctx context.Context, options client.ServerVersionOptions) (client.ServerVersionResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ServerVersion")
	}

	var r0 client.ServerVersionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ServerVersionOptions) (client.ServerVersionResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ServerVersionOptions) client.ServerVersionResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.ServerVersionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ServerVersionOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VolumeCreate provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) VolumeCreate(ctx context.Context, options client.VolumeCreateOptions) (client.VolumeCreateResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for VolumeCreate")
	}

	var r0 client.VolumeCreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.VolumeCreateOptions) (client.VolumeCreateResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.VolumeCreateOptions) client.VolumeCreateResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.VolumeCreateResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.VolumeCreateOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VolumeInspect provides a mock function with given fields: ctx, volumeID, options
func (_m *MockDockerClient) VolumeInspect(ctx context.Context, volumeID string, options client.VolumeInspectOptions) (client.VolumeInspectResult, error) {
	ret := _m.Called(ctx, volumeID, options)

	if len(ret) == 0 {
		panic("no return value specified for VolumeInspect")
	}

	var r0 client.VolumeInspectResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.VolumeInspectOptions) (client.VolumeInspectResult, error)); ok {
		return rf(ctx, volumeID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.VolumeInspectOptions) client.VolumeInspectResult); ok {
		r0 = rf(ctx, volumeID, options)
	} else {
		r0 = ret.Get(0).(client.VolumeInspectResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.VolumeInspectOptions) error); ok {
		r1 = rf(ctx, volumeID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VolumeList provides a mock function with given fields: ctx, options
func (_m *MockDockerClient) VolumeList(ctx context.Context, options client.VolumeListOptions) (client.VolumeListResult, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for VolumeList")
	}

	var r0 client.VolumeListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.VolumeListOptions) (client.VolumeListResult, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.VolumeListOptions) client.VolumeListResult); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(client.VolumeListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.VolumeListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VolumeRemove provides a mock function with given fields: ctx, volumeID, options
func (_m *MockDockerClient) VolumeRemove(ctx context.Context, volumeID string, options client.VolumeRemoveOptions) (client.VolumeRemoveResult, error) {
	ret := _m.Called(ctx, volumeID, options)

	if len(ret) == 0 {
		panic("no return value specified for VolumeRemove")
	}

	var r0 client.VolumeRemoveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.VolumeRemoveOptions) (client.VolumeRemoveResult, error)); ok {
		return rf(ctx, volumeID, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.VolumeRemoveOptions) client.VolumeRemoveResult); ok {
		r0 = rf(ctx, volumeID, options)
	} else {
		r0 = ret.Get(0).(client.VolumeRemoveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.VolumeRemoveOptions) error); ok {
		r1 = rf(ctx, volumeID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDockerClient creates a new instance of MockDockerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerClient {
	mock := &MockDockerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
