// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	serviceimage "github.com/irwinby/container-runtime-mcp/internal/service/image"
)

// MockImageService is an autogenerated mock type for the imageService type
type MockImageService struct {
	mock.Mock
}

// CanWrite provides a mock function with no fields
func (_m *MockImageService) CanWrite() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanWrite")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InspectImage provides a mock function with given fields: ctx, params
func (_m *MockImageService) InspectImage(ctx context.Context, params serviceimage.InspectImageParams) (serviceimage.ImageInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectImage")
	}

	var r0 serviceimage.ImageInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.InspectImageParams) (serviceimage.ImageInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.InspectImageParams) serviceimage.ImageInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(serviceimage.ImageInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, serviceimage.InspectImageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListImages provides a mock function with given fields: ctx, params
func (_m *MockImageService) ListImages(ctx context.Context, params serviceimage.ListImagesParams) ([]serviceimage.Image, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []serviceimage.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.ListImagesParams) ([]serviceimage.Image, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.ListImagesParams) []serviceimage.Image); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]serviceimage.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, serviceimage.ListImagesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullImage provides a mock function with given fields: ctx, params
func (_m *MockImageService) PullImage(ctx context.Context, params serviceimage.PullImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PullImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.PullImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PushImage provides a mock function with given fields: ctx, params
func (_m *MockImageService) PushImage(ctx context.Context, params serviceimage.PushImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PushImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.PushImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveImage provides a mock function with given fields: ctx, params
func (_m *MockImageService) RemoveImage(ctx context.Context, params serviceimage.RemoveImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.RemoveImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagImage provides a mock function with given fields: ctx, params
func (_m *MockImageService) TagImage(ctx context.Context, params serviceimage.TagImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TagImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceimage.TagImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
