// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	servicecontainer "github.com/irwinby/container-runtime-mcp/internal/service/container"
	mock "github.com/stretchr/testify/mock"
)

// MockContainerService is an autogenerated mock type for the containerService type
type MockContainerService struct {
	mock.Mock
}

// CanWrite provides a mock function with no fields
func (_m *MockContainerService) CanWrite() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanWrite")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ContainerLogs provides a mock function with given fields: ctx, params
func (_m *MockContainerService) ContainerLogs(ctx context.Context, params servicecontainer.ContainerLogsParams) (servicecontainer.ContainerLogsResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 servicecontainer.ContainerLogsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ContainerLogsParams) (servicecontainer.ContainerLogsResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ContainerLogsParams) servicecontainer.ContainerLogsResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(servicecontainer.ContainerLogsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicecontainer.ContainerLogsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) CreateContainer(ctx context.Context, params servicecontainer.CreateContainerParams) (string, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.CreateContainerParams) (string, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.CreateContainerParams) string); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicecontainer.CreateContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) ExecContainer(ctx context.Context, params servicecontainer.ExecContainerParams) (servicecontainer.ExecContainerResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ExecContainer")
	}

	var r0 servicecontainer.ExecContainerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ExecContainerParams) (servicecontainer.ExecContainerResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ExecContainerParams) servicecontainer.ExecContainerResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(servicecontainer.ExecContainerResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicecontainer.ExecContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InspectContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) InspectContainer(ctx context.Context, params servicecontainer.InspectContainerParams) (servicecontainer.ContainerInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainer")
	}

	var r0 servicecontainer.ContainerInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.InspectContainerParams) (servicecontainer.ContainerInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.InspectContainerParams) servicecontainer.ContainerInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(servicecontainer.ContainerInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicecontainer.InspectContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListContainers provides a mock function with given fields: ctx, params
func (_m *MockContainerService) ListContainers(ctx context.Context, params servicecontainer.ListContainersParams) ([]servicecontainer.Container, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []servicecontainer.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ListContainersParams) ([]servicecontainer.Container, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.ListContainersParams) []servicecontainer.Container); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]servicecontainer.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicecontainer.ListContainersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) RemoveContainer(ctx context.Context, params servicecontainer.RemoveContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.RemoveContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) RestartContainer(ctx context.Context, params servicecontainer.RestartContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RestartContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.RestartContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) StartContainer(ctx context.Context, params servicecontainer.StartContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.StartContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopContainer provides a mock function with given fields: ctx, params
func (_m *MockContainerService) StopContainer(ctx context.Context, params servicecontainer.StopContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, servicecontainer.StopContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockContainerService creates a new instance of MockContainerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerService {
	mock := &MockContainerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
