// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	servicevolume "github.com/irwinby/container-runtime-mcp/internal/service/volume"
	mock "github.com/stretchr/testify/mock"
)

// MockVolumeService is an autogenerated mock type for the volumeService type
type MockVolumeService struct {
	mock.Mock
}

// CanWrite provides a mock function with no fields
func (_m *MockVolumeService) CanWrite() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanWrite")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateVolume provides a mock function with given fields: ctx, params
func (_m *MockVolumeService) CreateVolume(ctx context.Context, params servicevolume.CreateVolumeParams) (servicevolume.VolumeInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateVolume")
	}

	var r0 servicevolume.VolumeInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.CreateVolumeParams) (servicevolume.VolumeInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.CreateVolumeParams) servicevolume.VolumeInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(servicevolume.VolumeInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicevolume.CreateVolumeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InspectVolume provides a mock function with given fields: ctx, params
func (_m *MockVolumeService) InspectVolume(ctx context.Context, params servicevolume.InspectVolumeParams) (servicevolume.VolumeInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectVolume")
	}

	var r0 servicevolume.VolumeInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.InspectVolumeParams) (servicevolume.VolumeInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.InspectVolumeParams) servicevolume.VolumeInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(servicevolume.VolumeInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicevolume.InspectVolumeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVolumes provides a mock function with given fields: ctx, params
func (_m *MockVolumeService) ListVolumes(ctx context.Context, params servicevolume.ListVolumesParams) ([]servicevolume.Volume, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []servicevolume.Volume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.ListVolumesParams) ([]servicevolume.Volume, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.ListVolumesParams) []servicevolume.Volume); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]servicevolume.Volume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicevolume.ListVolumesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveVolume provides a mock function with given fields: ctx, params
func (_m *MockVolumeService) RemoveVolume(ctx context.Context, params servicevolume.RemoveVolumeParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, servicevolume.RemoveVolumeParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockVolumeService creates a new instance of MockVolumeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeService {
	mock := &MockVolumeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
