// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	system "github.com/irwinby/container-runtime-mcp/internal/service/system"
	mock "github.com/stretchr/testify/mock"
)

// MockSystemService is an autogenerated mock type for the systemService type
type MockSystemService struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx
func (_m *MockSystemService) Ping(ctx context.Context) (system.PingResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 system.PingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (system.PingResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) system.PingResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(system.PingResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemInfo provides a mock function with given fields: ctx
func (_m *MockSystemService) SystemInfo(ctx context.Context) (system.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SystemInfo")
	}

	var r0 system.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (system.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) system.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(system.SystemInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemVersion provides a mock function with given fields: ctx
func (_m *MockSystemService) SystemVersion(ctx context.Context) (system.SystemVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SystemVersion")
	}

	var r0 system.SystemVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (system.SystemVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) system.SystemVersion); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(system.SystemVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSystemService creates a new instance of MockSystemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemService {
	mock := &MockSystemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
