// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	providers "github.com/irwinby/container-runtime-mcp/internal/provider"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderClient is an autogenerated mock type for the providerClient type
type MockProviderClient struct {
	mock.Mock
}

// CreateVolume provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) CreateVolume(ctx context.Context, params providers.CreateVolumeParams) (providers.VolumeInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateVolume")
	}

	var r0 providers.VolumeInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.CreateVolumeParams) (providers.VolumeInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.CreateVolumeParams) providers.VolumeInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.VolumeInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.CreateVolumeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InspectVolume provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) InspectVolume(ctx context.Context, params providers.InspectVolumeParams) (providers.VolumeInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectVolume")
	}

	var r0 providers.VolumeInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectVolumeParams) (providers.VolumeInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectVolumeParams) providers.VolumeInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.VolumeInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.InspectVolumeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVolumes provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) ListVolumes(ctx context.Context, params providers.ListVolumesParams) ([]providers.Volume, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []providers.Volume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListVolumesParams) ([]providers.Volume, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListVolumesParams) []providers.Volume); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Volume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.ListVolumesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveVolume provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) RemoveVolume(ctx context.Context, params providers.RemoveVolumeParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.RemoveVolumeParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProviderClient creates a new instance of MockProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderClient {
	mock := &MockProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
