// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	providers "github.com/irwinby/container-runtime-mcp/internal/provider"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderClient is an autogenerated mock type for the providerClient type
type MockProviderClient struct {
	mock.Mock
}

// ContainerLogs provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) ContainerLogs(ctx context.Context, params providers.ContainerLogsParams) (providers.ContainerLogsResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 providers.ContainerLogsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.ContainerLogsParams) (providers.ContainerLogsResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.ContainerLogsParams) providers.ContainerLogsResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.ContainerLogsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.ContainerLogsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) CreateContainer(ctx context.Context, params providers.CreateContainerParams) (string, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.CreateContainerParams) (string, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.CreateContainerParams) string); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.CreateContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) ExecContainer(ctx context.Context, params providers.ExecContainerParams) (providers.ExecContainerResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ExecContainer")
	}

	var r0 providers.ExecContainerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.ExecContainerParams) (providers.ExecContainerResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.ExecContainerParams) providers.ExecContainerResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.ExecContainerResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.ExecContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InspectContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) InspectContainer(ctx context.Context, params providers.InspectContainerParams) (providers.ContainerInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainer")
	}

	var r0 providers.ContainerInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectContainerParams) (providers.ContainerInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectContainerParams) providers.ContainerInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.ContainerInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.InspectContainerParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListContainers provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) ListContainers(ctx context.Context, params providers.ListContainersParams) ([]providers.Container, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []providers.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListContainersParams) ([]providers.Container, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListContainersParams) []providers.Container); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.ListContainersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) RemoveContainer(ctx context.Context, params providers.RemoveContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.RemoveContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) RestartContainer(ctx context.Context, params providers.RestartContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RestartContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.RestartContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) StartContainer(ctx context.Context, params providers.StartContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.StartContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopContainer provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) StopContainer(ctx context.Context, params providers.StopContainerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.StopContainerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProviderClient creates a new instance of MockProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderClient {
	mock := &MockProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
