// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	providers "github.com/irwinby/container-runtime-mcp/internal/provider"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderClient is an autogenerated mock type for the providerClient type
type MockProviderClient struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx
func (_m *MockProviderClient) Ping(ctx context.Context) (providers.PingResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 providers.PingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (providers.PingResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) providers.PingResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(providers.PingResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemInfo provides a mock function with given fields: ctx
func (_m *MockProviderClient) SystemInfo(ctx context.Context) (providers.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SystemInfo")
	}

	var r0 providers.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (providers.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) providers.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(providers.SystemInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemVersion provides a mock function with given fields: ctx
func (_m *MockProviderClient) SystemVersion(ctx context.Context) (providers.SystemVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SystemVersion")
	}

	var r0 providers.SystemVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (providers.SystemVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) providers.SystemVersion); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(providers.SystemVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockProviderClient creates a new instance of MockProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderClient {
	mock := &MockProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
