// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	providers "github.com/irwinby/container-runtime-mcp/internal/provider"
)

// MockProviderClient is an autogenerated mock type for the providerClient type
type MockProviderClient struct {
	mock.Mock
}

// InspectImage provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) InspectImage(ctx context.Context, params providers.InspectImageParams) (providers.ImageInspect, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InspectImage")
	}

	var r0 providers.ImageInspect
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectImageParams) (providers.ImageInspect, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.InspectImageParams) providers.ImageInspect); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(providers.ImageInspect)
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.InspectImageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListImages provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) ListImages(ctx context.Context, params providers.ListImagesParams) ([]providers.Image, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []providers.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListImagesParams) ([]providers.Image, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, providers.ListImagesParams) []providers.Image); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, providers.ListImagesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullImage provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) PullImage(ctx context.Context, params providers.PullImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PullImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.PullImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PushImage provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) PushImage(ctx context.Context, params providers.PushImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PushImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.PushImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveImage provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) RemoveImage(ctx context.Context, params providers.RemoveImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.RemoveImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagImage provides a mock function with given fields: ctx, params
func (_m *MockProviderClient) TagImage(ctx context.Context, params providers.TagImageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TagImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, providers.TagImageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProviderClient creates a new instance of MockProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderClient {
	mock := &MockProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
